### ISSUE TITLE
Crash on detail view

### ISSUE THREAD

**Issue by calllib** [ubipo/osmfocus#23]
When pressing any framed OSM element description, a new full-screen info is briefly shown before the app crashes.

Error code presented:
"Incorrect resolution sequence for Java constructor public constructor i() defined in m6.i[c@c237c6b] (x3.j: class m6.i)"

App version: 1.1.2-fdroid
OS: LineageOS 18.1-20211019 (Android 11)

**Comment by ubipo** [comment]
00dd435 will be released with v1.2.0

Root problem was R8 minimizing classes used by Klaxon though reflection.

Relevant stack trace for reference:
```
n3.z: Incorrect resolution sequence for Java constructor public constructor i() defined in m6.i[c@5e6cf44] (x3.j: class m6.i)
	at n3.f0.g(RuntimeTypeMapper.kt:23)
	at n3.k.<init>(KFunctionImpl.kt:8)
	at n3.g$a$e.a(KClassImpl.kt:5)
	at n3.g$a$e.l(KClassImpl.kt:1)
	at n3.b0$a.c(ReflectProperties.java:4)
	at n3.b0$c.b(ReflectProperties.java:1)
	at n3.g$a.k(Unknown Source:7)
	at n3.g.m(KClassImpl.kt:1)
	at k1.l.h(JsonObjectConverter.kt:14)
	at k1.l.d(JsonObjectConverter.kt:3)
	at k1.d.h(DefaultConverter.kt:38)
	at k1.d.a(DefaultConverter.kt:17)
	at k1.p.g(Klaxon.kt:9)
	at m6.b.c(api.kt:22)
	at m6.b$b.i(Unknown Source:16)
	at w2.a.o(ContinuationImpl.kt:3)
	at u5.a1.run(DispatchedTask.kt:22)
	at kotlinx.coroutines.scheduling.a.y(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.c(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.m(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.run(CoroutineScheduler.kt:1)
```
