### ISSUE TITLE
dispatchCancelPendingInputEvents() NPE

### ISSUE THREAD

**Issue by ubipo** [ubipo/osmfocus#31]
Not immediately sure what went wrong here. Combination of the exception reporter activity and the element details taglist is pretty odd.

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchCancelPendingInputEvents()' on a null object reference
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4709)
	at android.view.View.cancelPendingInputEvents(View.java:20737)
	at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:5366)
	at android.app.Activity.startActivityForResult(Activity.java:5345)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5284)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:5670)
	at android.app.Activity.startActivity(Activity.java:5623)
	at net.pfiers.osmfocus.view.MainActivity.handleException(MainActivity.kt:10)
	at net.pfiers.osmfocus.view.fragments.ElementDetailsFragment$onCreateView$tagsListAdapter$1$1.invokeSuspend(ElementDetailsFragment.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

```

**Comment by ubipo** [comment]
We moved from using `Activity` to using `Application` as the context for stuff that doesn't need a UI context (see [`AppContextSingletonDelegate.getValue()`](https://github.com/ubipo/osmfocus/blob/4a395afd52a45d073a94c453bfce2128c74690b0/app/src/main/java/net/pfiers/osmfocus/service/util/appContextSingleton.kt#L23)).

As a result we're no longer using `Activity.startActivity` in the thread default exception handler. The `Application` context implementation (`android.app.Instrumentation.execStartActivity()`) doesn't ever call `cancelInputsAndStartExitTransition` so this bug can't occur anymore. Hooray.
