### ISSUE TITLE
Unhandled exception: timeout

### ISSUE THREAD

**Issue by ubipo** [ubipo/osmfocus#36]
Reported via email.

Timeout during a network request, should show a "Request took too long. Retry?" snackbar or something.

Version 140.

Stacktrace:
```
timeout
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:5)
	com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:35)
Caused by: java.net.SocketTimeoutException: timeout
	com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	com.android.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:441)
	com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
	com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:103)
	com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:64)
	com.android.okhttp.okio.GzipSource.read(GzipSource.java:82)
	com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
	java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	java.io.FilterInputStream.read(FilterInputStream.java:133)
	com.github.kittinunf.fuel.util.ProgressInputStream.read(ProgressInputStream.kt:1)
	java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	java.io.FilterInputStream.read(FilterInputStream.java:107)
	com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:6)
	com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:3)
	com.github.kittinunf.fuel.core.deserializers.StringDeserializer.deserialize(StringDeserializer.kt:2)
	com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:13)
	net.pfiers.osmfocus.service.osmapi.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:5)
	at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:35)
Caused by: java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:441)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
	at com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:103)
	at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:64)
	at com.android.okhttp.okio.GzipSource.read(GzipSource.java:82)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.github.kittinunf.fuel.util.ProgressInputStream.read(ProgressInputStream.kt:1)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:6)
	at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:3)
	at com.github.kittinunf.fuel.core.deserializers.StringDeserializer.deserialize(StringDeserializer.kt:2)
	at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:13)
	at net.pfiers.osmfocus.service.osmapi.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:194)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	... 24 more

```

**Comment by ubipo** [comment]
Fixed in [v1.5.1](https://github.com/ubipo/osmfocus/releases/tag/v1.5.1)
