### ISSUE TITLE
NPE in osmapi.Conversion

### ISSUE THREAD

**Issue by ubipo** [ubipo/osmfocus#42]
Occured around Quarter Jack Surgery in Wimborne.

This is probably because one of the element fields like `username` is not present.

Stacktrace:
```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at net.pfiers.osmfocus.service.osmapi.ConversionKt.jsonToElements(conversion.kt:71)
	at net.pfiers.osmfocus.service.osmapi.ElementsDownloadManager.processDownload(ElementsDownloadManager.kt:1)
	at net.pfiers.osmfocus.service.osmapi.EnvelopeDownloadManager$download$result$1$1.invokeSuspend(EnvelopeDownloadManager.kt:2)
```

**Comment by hamishmb** [comment]
Cheers for making the GitHub issue :)
