### ISSUE TITLE
Unhandled exception "timeout"

### ISSUE THREAD

**Issue by hamishmb** [ubipo/osmfocus#45]
<h2> Exception details</h2>
Message: `timeout`

<h2> What happened / what actions did you take before the bug occurred?</h2>
Just looking around the One Stop near Canford Bottom roundabout near Dales Drive (Dorset area, near Wimborne).

<h2> Comments</h2>
Seems similar to https://github.com/ubipo/osmfocus/issues/36, not sure if a duplicate or not.

System info:

App version: 1.5.0-fdroid
App version code: 150
App build type: release
Android version: 30
Device name: motorola moto g(8) power

Stack trace:

`timeout
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:3)
	com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:35)
	net.pfiers.osmfocus.service.taginfo.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: timeout
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:5)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:5)
Caused by: java.net.SocketTimeoutException: timeout
	com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
	com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
	com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
	com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:75)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:2)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:5)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:10)
	com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:8)
	net.pfiers.osmfocus.service.taginfo.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:3)
	at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:35)
	at net.pfiers.osmfocus.service.taginfo.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: timeout
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:5)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:5)
Caused by: java.net.SocketTimeoutException: timeout
	com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
	com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
	com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
	com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:75)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:2)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:5)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:10)
	com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:8)
	net.pfiers.osmfocus.service.taginfo.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:5)
	at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:5)
Caused by: java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
	at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:75)
	at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:2)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:5)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:10)
	at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:8)
	at net.pfiers.osmfocus.service.taginfo.ApiKt$apiReq$$inlined$awaitStringResponseResult$default$1.invokeSuspend(Coroutines.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	... 23 more`

**Comment by ubipo** [comment]
Fixed in [v1.5.1](https://github.com/ubipo/osmfocus/releases/tag/v1.5.1)
